- src-tauri/src/main.rs
仿照大佬的写法，实现双击顶部全屏，功能实现了，本地运行没有问题。
> ✨ 支持双击顶部全屏

- README.md
- README_EN.md
> add product links

- src-tauri/src/main.rs
- src-tauri/src/pake.js
#39
> 1、代码架构优化，可以将注入的 css、注入的 js 通过文件方式分开，~~同时所有配置可以放到 tauri.config.json 里面~~
有考虑过将 CSS 也单独提取出来，目前还没想好怎么做
> 🧑‍💻 将 JS 和 CSS 代码提取到单独的文件中

- src-tauri/src/main.rs
1.  呼应 REDEME.md 描述，增加了从 *tauri.config.json* 中读取 `fullscreen` 来做窗口初始化设置的功能
2. 将获取 `WindowsConfig` 部分的代码从 `main` 中抽离
> :sparkles: 支持从 *tauri.config.json* 中读取 `fullscreen` 来做窗口初始化设置

- README.md
- README_EN.md
- package.json
- src-tauri/Cargo.toml
- src-tauri/src/main.rs
- feat: Make devtools a feature
- feat(npm): Add “dev:withtool” script
- docs: Update description of DevTools
This closes #67.
> DevTools as feature

- .github/ISSUE_TEMPLATE/bug.md
> docs(template): Better English description

- CONTRIBUTING.md
> docs(contrib): Use Mermaid to draw flowcharts

- .ecrc.json
- .editorconfig
- .github/FUNDING.yml
- .github/ISSUE_TEMPLATE/bug.md
- .github/workflows/editorconfig-check.yml
- .github/workflows/main.yml
- .github/workflows/rust-code-quality-check.yml
- .prettierignore
- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
- README.md
- README_EN.md
- dist/twitter.css
- script/build.bat
- script/build.sh
- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/build.rs
- src-tauri/src/main.rs
- src-tauri/src/pake.js
- src-tauri/tauri.conf.json
- 运行 `cargo clippy`，采纳更简洁的代码写法 910cc0a
- 藉由 ShellCheck 发现并修正 `build.sh` 潜在的代码问题 fe39755
- 运行 `cargo fmt` 保持整个 codebase 的排版风格一致 8362dbc
- 运行 `prettier` 统一代码风格，同时修正其他与 EditorConfig 不符的排版风格 20cc0f6
- 优化 `template/bug.md` 的英语叙述 121881f (中文對照翻譯見 #92)
- 在文档内用 Mermaid 绘制贡献流程 e8a0139 (一般讀者看到的流程圖見 #95)
- 把 Pake 的依赖更新到相容的最新版本 5b36097
- 加入 `.editorconfig`、Prettier 配置和 EditorConfig 的持续整合 (CI) 检查配置 dd5ef73
- 导入 Rust 端代码风格 (fmt)、单测 (test) 和问题检查 (clippy) CI b1c7ff8
- 导入「检查文件的排版风格是否符合 EditorConfig」的检查 CI 064de9b
> Meta Pull Request: Codebase Improvement

- bin/README_EN.md
Signed-off-by: Aiello <Aiello.Chan@Gmail.com>
> fix(doc): Add icon download site

- bin/README.md
Signed-off-by: Aiello <Aiello.Chan@Gmail.com>
> fix(doc): Add icon download url

- README.md
Signed-off-by: pan93412 <pan93412@gmail.com>
> docs(en): Typo correction

- README.md
- README_CN.md
Emphasize different fields in different files.
I hope this modification can make people understand more easily and directly.
> docs(cn/en): Optimizing Document Field Prompts

- CODE_OF_CONDUCT.md
- README.md
- README_CN.md
- bin/utils/url.ts
- script/build.sh
> Typo and Spelling Correction

- src-tauri/src/inject/event.js
详情参照 https://github.com/tw93/Pake/discussions/455#discussioncomment-6108416
> fix: 解决 addEventListener 不能捕获未 append 到文档的 a 标签点击事件导致的丢失下载功能问题。

- .github/workflows/pake-cli.yaml
- .github/workflows/pake_build.yaml
- .github/workflows/pake_build_with_cache.yaml
This removes the manual configuration and uses an action that does it automatically.
> Use better caching action in github actions

- README_CN.md
在您的浏览器中在Google Colab上运行Pake。
这样用户可以在他们的浏览器中尝试它，然后再在本地系统上运行。
> 将Pake添加到Google Colab上并进行翻译。

- src-tauri/src/inject/event.js
> Fix ChatGPT New UI

- .dockerignore
- .github/workflows/docker-publish.yml
- Dockerfile
- README.md
Simplifies CLI usage on linux.
- Dockerfile
- workflow to build and publish image in github packages
- readme entry
P.S. unfortunately I started from `master` branch. Due to many diffs in `dev`, merging seems to be inappropriate now
> Add docker image for linux

- bin/cli.ts
close #889.
Reference: https://github.com/tj/commander.js/blob/master/Readme.md#variadic-option .
> 🐛 Update `inject` definition in command line options.

- src-tauri/Cargo.lock
- src-tauri/Cargo.toml
- src-tauri/pake.json
- src-tauri/src/inject/event.js
- Resolves null pointer dereference crash on Windows platform
- Fixes issue where app crashes with STATUS_STACK_BUFFER_OVERRUN
- Updates from v2.2.0 to v2.2.4 which includes upstream bugfix
- Improves app stability during startup and reload operations
> 🔧 fix: update tauri-plugin-single-instance to v2.2.4
